# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows_VS2017_x64
  pool:
      vmImage: 'vs2017-win2016'
  steps:
    - script: |
        git clone https://github.com/caioteixeira/PhysicsPlayground.git
        mkdir build
        cd build
        cmake -G "Visual Studio 15 Win64" -DCMAKE_BUILD_TYPE=Release ../PhysicsPlayground
      displayName: Clone and generate project
    - task: MSBuild@1
      inputs:
        solution: 'build/ALL_BUILD.vcxproj'
        maximumCpuCount: true
        platform: 'x64'
        configuration: 'Release'
      displayName: Build PhysicsPlayground